version: "3.8"
   
services:
  api:
    image: meiyih/getting-star-arcface:latest 
    command: pipenv run uvicorn app.main:app --host 0.0.0.0 --port 5000 # add --reload for development
    volumes:
      - ./app:/app/   # for development purpose
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment: 
      - DATABASE_URL=postgres://postgres:password@db/insightface_db
      - CREATE_ALL_EACH_RUN=True
      - DROP_ALL_EACH_RUN=False   # set to True for development
      - DEBUG=True
  db:
    image: jeremyleo/postgres-2k-cube:13.1 #The cube extension, which perform operations on vectors, has a hard limit of 100 dimensions per vector in `postgres` image
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=insightface_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
       - ./data:/var/lib/postgresql/data
      
      
